export enum EnumMessages {
  SAVING_SUCCESS = 'ذخیره سازی موفق',
  SAVING_FAILURE = 'ذخیره سازی ناموفق',
  UPDATING_SUCCESS = 'بروزرسانی موفق',
  UPDATING_FAILURE = 'بروززسانی ناموفق',
  DELETING_SUCCESS = 'حذف موفق',
  DELETING_FAILURE = 'حذف ناموفق',
  GET_SUCCESS = 'دیتا یافت شد',
  GET_FAILURE = 'دیتایی یافت نشد',
  INVALID_ID = 'آی دی نامعتبر',
  DUPLICATE_DATA = 'دیتای تکراری',
  LOGIN_INCORRECT_MOBILE_OR_PASSWORD = 'اطلاعات ورود اشتباه است',
  BLOCK = 'شما بلاک شده اید. با پشتیبانی تماس بگیرید',
  INVALID_EMAIL = 'ایمیل نامعتبر',
  INVALID_MOBILE = 'موبایل نامعتبر',
  PASSWORD_MUST_BE_6_CHARACTERS = 'پسورد باید حداقل 6 کاراکتر باشد ',
  EMPTY_FIELD = 'فیلد خالی',
  CHECK_THE_FIELD = 'ورودی اشتباه',
  INVALID_ENUM = 'محدودیت  کلمات',
  INVALID_TYPE = 'نوع ورودی اشتباه است',
  NO_TOKEN = 'NO_TOKEN',
  USE_ID = 'داکیومنت در جای دیگه استفاده شده',
}
