image: node:14.14.0
cache:
  # untracked: true
  paths:
    - node_modules/
stages:
  - install
  - test
  - build
  - deploy

# install:
#   stage: install
#   variables:
#     GIT_STRATEGY: clone

#   script:
#   - npx prisma generate
#   - npm install

# tests:
#   stage: test
#   variables:
#     GIT_STRATEGY: none
#   dependencies:
#     - install
#   script:
#     - npm run test
#   coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - docker build -t bime/backend .

deploy:
  # type: deploy
  variables:
    GIT_STRATEGY: none
  stage: deploy
  dependencies:
    - build
  script:
    - docker-compose down
    - docker-compose up -d
    - docker image prune
