image: docker
cache:
  # untracked: true
  paths:
    - node_modules/
stages:
  - test
  - build
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - docker build -t bime-api-prod:1.0.0 .
deploy:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  dependencies:
    - build
  script:
    # - docker-compose down
    - docker-compose up -d dev
    # - docker-compose up -d prod
    - docker image prune
