version: '3.7'
services:
  mongodb:
    restart: always
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    # - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
    ports:
      - '27018:27017'
    container_name: mongodb
  bime-backend:
    restart: always
    image: bime/backend
    # container_name: bime-backend
    # build: .
    ports:
      - '3000:3000'
    container_name: bime-backend
    # environment:
    # - NODE_ENV=production
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: password
    #   MYSQL_HOST: mysql
    #   MYSQL_DATABASE: prisma
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./files:/app/files
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

    working_dir: /app
    # restart: 'unless-stopped'
volumes:
  data:
  logs:
  files:
