version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./data:/data/db
  dev:
    image: bime-api-dev:1.0.0
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./env/backend.env
    restart: unless-stopped

  prod:
    image: bime-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  data:
  logs:
  files:
